services:
  postgres:
    image: "postgres:16"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "mbdatabase"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  database-data:
  pgadmin_data:
  redis_data:
